services:
  multi-diagram-viewer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./diagrams:/app/diagrams:ro
    environment:
      - DIAGRAMS_DIR=/app/diagrams
    restart: unless-stopped 